on: push
name: Sonarqube
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.1.0
      with:
        projectBaseDir: "/src"
        projectKey: "Uasoft-LMS-Module"
        host: "https://sonarqube.cs.ui.ac.id"
        login: "7029081132e2359ad09d1802c21cee9235797cf3"
